name: Cypress test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # Add any specific Cypress command line options you need
          # For example, to run only a specific file:
          spec: cypress/integration/randomlogin.cy.js